/*******************************************************************************
 * Copyright (c) 2012 Christian Gawron.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 11:37:11 AM MEZ 
//


package de.cgawron.xspf.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.cgawron.xspf.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Playlist_QNAME = new QName("http://xspf.org/ns/0/", "playlist");
    private final static QName _AttributionTypeLocation_QNAME = new QName("http://xspf.org/ns/0/", "location");
    private final static QName _AttributionTypeIdentifier_QNAME = new QName("http://xspf.org/ns/0/", "identifier");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.cgawron.xspf.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

    /**
     * Create an instance of {@link TrackListType }
     * 
     */
    public TrackListType createTrackListType() {
        return new TrackListType();
    }

    /**
     * Create an instance of {@link TrackType }
     * 
     */
    public TrackType createTrackType() {
        return new TrackType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link AttributionType }
     * 
     */
    public AttributionType createAttributionType() {
        return new AttributionType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link PlaylistType }
     * 
     */
    public PlaylistType createPlaylistType() {
        return new PlaylistType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaylistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xspf.org/ns/0/", name = "playlist")
    public JAXBElement<PlaylistType> createPlaylist(PlaylistType value) {
        return new JAXBElement<PlaylistType>(_Playlist_QNAME, PlaylistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xspf.org/ns/0/", name = "location", scope = AttributionType.class)
    public JAXBElement<String> createAttributionTypeLocation(String value) {
        return new JAXBElement<String>(_AttributionTypeLocation_QNAME, String.class, AttributionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xspf.org/ns/0/", name = "identifier", scope = AttributionType.class)
    public JAXBElement<String> createAttributionTypeIdentifier(String value) {
        return new JAXBElement<String>(_AttributionTypeIdentifier_QNAME, String.class, AttributionType.class, value);
    }

}
