//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 11:37:11 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xspf.org/ns/0/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.cgawron.xspf.model;
