/*******************************************************************************
 * Copyright (c) 2012 Christian Gawron.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 11:37:11 AM MEZ 
//


package de.cgawron.xspf.model;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PlaylistType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlaylistType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="annotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="license" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="attribution" type="{http://xspf.org/ns/0/}AttributionType" minOccurs="0"/>
 *         &lt;element name="link" type="{http://xspf.org/ns/0/}LinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="meta" type="{http://xspf.org/ns/0/}MetaType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://xspf.org/ns/0/}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trackList" type="{http://xspf.org/ns/0/}TrackListType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://xspf.org/ns/0/}VersionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlaylistType", propOrder = {
    "title",
    "creator",
    "annotation",
    "info",
    "location",
    "identifier",
    "image",
    "date",
    "license",
    "attribution",
    "link",
    "meta",
    "extension",
    "trackList"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
public class PlaylistType {

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String title;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String creator;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String annotation;
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String info;
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String location;
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String identifier;
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String image;
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected XMLGregorianCalendar date;
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String license;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected AttributionType attribution;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected List<LinkType> link;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected List<MetaType> meta;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected List<ExtensionType> extension;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected TrackListType trackList;
    @XmlAttribute(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    protected String version;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setAnnotation(String value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setInfo(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setLicense(String value) {
        this.license = value;
    }

    /**
     * Gets the value of the attribution property.
     * 
     * @return
     *     possible object is
     *     {@link AttributionType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public AttributionType getAttribution() {
        return attribution;
    }

    /**
     * Sets the value of the attribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributionType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setAttribution(AttributionType value) {
        this.attribution = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public List<LinkType> getLink() {
        if (link == null) {
            link = new ArrayList<LinkType>();
        }
        return this.link;
    }

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public List<MetaType> getMeta() {
        if (meta == null) {
            meta = new ArrayList<MetaType>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the trackList property.
     * 
     * @return
     *     possible object is
     *     {@link TrackListType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public TrackListType getTrackList() {
        return trackList;
    }

    /**
     * Sets the value of the trackList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrackListType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setTrackList(TrackListType value) {
        this.trackList = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-11-15T11:37:11+01:00", comments = "JAXB RI vJAXB 2.1.10")
    public void setVersion(String value) {
        this.version = value;
    }

}
